### ISSUE TITLE
Cannot clone on Windows

### ISSUE THREAD

**Issue by resir014** [sonnylazuardi/gramatika.app#1]
Hey @sonnylazuardi! I was about to clone the project and contribute some accessibility improvements to the website, however I can't seem to be able to clone the project on Windows. It throws some errors for `:Zone.Identifier` files, which I believe is an illegal file format on Windows because of the `:` character:

![image](https://user-images.githubusercontent.com/5663877/147845119-6729e319-4e73-4ab6-bc7a-8a77553ebc01.png)

**Comment by sonnylazuardi** [comment]
@resir014 hey can you try again? I removed those files

**Comment by resir014** [comment]
@sonnylazuardi Yep, all works now. Thank you! 💙
